name: Release & Deploy

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: mwae_cloud
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: false
          tags: |
            ghcr.io/cubexy/ctrl-knit:${{ github.event.release.tag_name }}
            ghcr.io/cubexy/ctrl-knit:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=ctrl-knit container image
            org.opencontainers.image.licenses=MIT

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: mwae_cloud
    steps:
      - name: SSH to server and update
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd data/docker
            docker compose pull ctrl-knit
            docker compose up -d ctrl-knit
